database.server=localhost
database.name=gridscore
database.username=root
database.password=
database.port=

plausible.hash.mode=
plausible.domain=
plausible.api.host=

plausible.server.exception.domain=
plausible.server.exception.host=

trial.expiry.days=365

config.folder=

secure.token=