/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen;


import java.util.Arrays;
import java.util.List;

import jhi.gridscore.server.database.codegen.tables.SchemaVersion;
import jhi.gridscore.server.database.codegen.tables.Trials;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GridscoreDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gridscore_db</code>
     */
    public static final GridscoreDb GRIDSCORE_DB = new GridscoreDb();

    /**
     * No further instances allowed
     */
    private GridscoreDb() {
        super("gridscore_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SchemaVersion.SCHEMA_VERSION,
            Trials.TRIALS
        );
    }
}
