/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen;


import jhi.gridscore.server.database.codegen.tables.SchemaVersion;
import jhi.gridscore.server.database.codegen.tables.Trials;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in gridscore_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TRIALS_EDITOR_CODE = Internal.createIndex(DSL.name("editor_code"), Trials.TRIALS, new OrderField[] { Trials.TRIALS.EDITOR_CODE }, false);
    public static final Index TRIALS_OWNER_CODE = Internal.createIndex(DSL.name("owner_code"), Trials.TRIALS, new OrderField[] { Trials.TRIALS.OWNER_CODE }, false);
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Internal.createIndex(DSL.name("schema_version_s_idx"), SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
    public static final Index TRIALS_VIEWER_CODE = Internal.createIndex(DSL.name("viewer_code"), Trials.TRIALS, new OrderField[] { Trials.TRIALS.VIEWER_CODE }, false);
}
