/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import jhi.gridscore.server.pojo.Trial;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trials implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        ownerCode;
    private String        editorCode;
    private String        viewerCode;
    private Trial         trial;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Trials() {}

    public Trials(Trials value) {
        this.ownerCode = value.ownerCode;
        this.editorCode = value.editorCode;
        this.viewerCode = value.viewerCode;
        this.trial = value.trial;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Trials(
        String        ownerCode,
        String        editorCode,
        String        viewerCode,
        Trial         trial,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.ownerCode = ownerCode;
        this.editorCode = editorCode;
        this.viewerCode = viewerCode;
        this.trial = trial;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>gridscore_db.trials.owner_code</code>.
     */
    public String getOwnerCode() {
        return this.ownerCode;
    }

    /**
     * Setter for <code>gridscore_db.trials.owner_code</code>.
     */
    public void setOwnerCode(String ownerCode) {
        this.ownerCode = ownerCode;
    }

    /**
     * Getter for <code>gridscore_db.trials.editor_code</code>.
     */
    public String getEditorCode() {
        return this.editorCode;
    }

    /**
     * Setter for <code>gridscore_db.trials.editor_code</code>.
     */
    public void setEditorCode(String editorCode) {
        this.editorCode = editorCode;
    }

    /**
     * Getter for <code>gridscore_db.trials.viewer_code</code>.
     */
    public String getViewerCode() {
        return this.viewerCode;
    }

    /**
     * Setter for <code>gridscore_db.trials.viewer_code</code>.
     */
    public void setViewerCode(String viewerCode) {
        this.viewerCode = viewerCode;
    }

    /**
     * Getter for <code>gridscore_db.trials.trial</code>.
     */
    public Trial getTrial() {
        return this.trial;
    }

    /**
     * Setter for <code>gridscore_db.trials.trial</code>.
     */
    public void setTrial(Trial trial) {
        this.trial = trial;
    }

    /**
     * Getter for <code>gridscore_db.trials.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>gridscore_db.trials.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>gridscore_db.trials.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>gridscore_db.trials.updated_on</code>.
     */
    public void setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trials (");

        sb.append(ownerCode);
        sb.append(", ").append(editorCode);
        sb.append(", ").append(viewerCode);
        sb.append(", ").append(trial);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
